[package]
name = "randsleep"
version = "0.1.0"
authors = ["Andy <andy@slivers.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8"
clap = "3.0.0-beta.2"  